---
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-dev
    restart:
      unless-stopped
      #ports:
      #  - "8085:80"
    networks:
      - proxy

networks:
  proxy:
    external: true
